---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: jenkins-rs
 labels:
  author: nani
  type: jenkinserver
spec:
 replicas: 2
 selector:
  matchLabels:
   type: jenkinserver
 template:
  metadata:
   name: jenkins-pod
   labels:
    type: jenkinserver
  spec:
   containers:
    - name: jenser
      image: jenkins
      ports:
       - containerPort: 8080
         hostPort: 8888
